### ISSUE TITLE
关于发布h5

### ISSUE THREAD

**Issue by LiuYuNan01** [VYuLinLin/doudizhu-stand-alone#1]
你好 能告知怎么发布h5吗 之前都是发布安卓 微信 没有发布过h5

**Comment by VYuLinLin** [comment]
![image](https://user-images.githubusercontent.com/28807436/91439676-f8cf4a00-e89f-11ea-9c25-6cc8d622ff92.png)
构建发布的时候选择Web Mobile就好了
